services:
  spark-master:
    build: .
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-logs:${SPARK_EVENTS}
    ports:
      - "5186:5186"  
      - "7077:7077"   
      - "4040:4040"   
    networks:
      - spark-net

  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
    volumes:
      - ./spark-logs:${SPARK_EVENTS}
    ports:
      - "5187:5187"  
      - "4041:4040"
    networks:
      - spark-net
    depends_on:
      - spark-master

  spark-history:
    build: .
    environment:
      - SPARK_MODE=history
    volumes:
      - ./spark-logs:${SPARK_EVENTS}
    ports:
      - '18080:18080'  
    networks:
      - spark-net
    depends_on:
      - spark-master
networks:
  spark-net:
    driver: bridge