services:
  spark-master:
    build: .
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "5186:5186"   # UI do Spark Master
      - "7077:7077"   # Porta de comunicação do Master com os Workers
      - "4040:4040"   # Porta de Monitoramento
    networks:
      - spark-net

  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
    volumes:
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "5187:5187"   # UI do Spark Worker
      - "4041:4040"
    networks:
      - spark-net
    depends_on:
      - spark-master

  spark-history:
    build: .
    environment:
      - SPARK_MODE=history
    volumes:
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'  
    networks:
      - spark-net
    depends_on:
      - spark-master
networks:
  spark-net:
    driver: bridge